from app.models.state import ResearchState
from app.services.llm import ask_llm


def report_node(state: ResearchState):

    # ==================================================
    # SOURCE DATA
    # ==================================================

    location = state["recommendation"]
    locations = state["locations"]

    if not locations:
        raise ValueError("No locations available for report generation.")

    # --------------------------------------------------
    # Find recommended location
    # --------------------------------------------------

    best_location_data = next(
        (
            loc
            for loc in locations
            if loc.get("name") == location
        ),
        None,
    )

    if best_location_data is None:
        raise ValueError(
            f"Recommended location '{location}' was not found "
            "in the evaluated locations."
        )

    # ==================================================
    # AUTHORITATIVE SCORE
    #
    # The scoring engine is the ONLY source of truth.
    # The LLM is never allowed to calculate or modify it.
    # ==================================================

    try:
        score = float(
            best_location_data["suitability_score"]
        )
    except (KeyError, TypeError, ValueError):
        raise ValueError(
            f"Invalid suitability score for '{location}'."
        )

    score_text = f"{score:.2f}"

    # ==================================================
    # AUTHORITATIVE RANKING
    #
    # Ranking is calculated by the application,
    # never by the LLM.
    # ==================================================

    sorted_locations = sorted(
        locations,
        key=lambda loc: float(
            loc.get("suitability_score", 0)
        ),
        reverse=True,
    )

    ranking = next(
        (
            index + 1
            for index, loc in enumerate(sorted_locations)
            if loc.get("name") == location
        ),
        None,
    )

    if ranking is None:
        raise ValueError(
            f"Unable to determine ranking for '{location}'."
        )

    # ==================================================
    # SECOND-RANKED LOCATION
    # ==================================================

    second_location = None
    second_score = None
    score_difference = None

    if ranking > 1:
        # If recommendation is not first,
        # compare against the location immediately above it.
        second_location = sorted_locations[ranking - 2]

    elif len(sorted_locations) > 1:
        # Recommended location is first.
        second_location = sorted_locations[1]

    if second_location is not None:
        try:
            second_score = float(
                second_location.get(
                    "suitability_score",
                    0
                )
            )

            score_difference = round(
                abs(score - second_score),
                2
            )

        except (TypeError, ValueError):
            second_score = None
            score_difference = None

    # ==================================================
    # LOCKED METRICS
    # ==================================================

    temperature = best_location_data.get(
        "temperature"
    )

    cooling_score = best_location_data.get(
        "cooling_score"
    )

    thermal_score = best_location_data.get(
        "thermal_score"
    )

    solar_ghi = best_location_data.get(
        "solar_ghi"
    )

    solar_dni = best_location_data.get(
        "solar_dni"
    )

    # ==================================================
    # RANKING DATA FOR LLM
    #
    # Only expose the information needed for writing.
    # ==================================================

    ranking_data = [
        {
            "rank": index + 1,
            "location": loc.get("name"),
            "suitability_score": (
                f"{float(loc.get('suitability_score', 0)):.2f}"
            ),
        }
        for index, loc in enumerate(sorted_locations)
    ]

    # ==================================================
    # RANKING STATEMENT
    #
    # This is generated by the application, not the LLM.
    # ==================================================

    if ranking == 1:
        ranking_statement = (
            f"{location} ranked first among the evaluated candidates "
            "based on the provided scoring metrics."
        )
    else:
        ranking_statement = (
            f"{location} ranked #{ranking} among the evaluated candidates "
            "based on the provided scoring metrics."
        )

    # ==================================================
    # AI REPORT PROMPT
    # ==================================================

    prompt = f"""
You are the REPORT WRITER inside AIXLocate.

You are NOT the decision maker.

The application has already completed the climate
analysis, scoring, recommendation, and ranking.

Your ONLY task is to convert the supplied AUTHORITATIVE
FACTS into ONE short, professional, factual paragraph.

The application values below are immutable.

==================================================
AUTHORITATIVE DECISION
==================================================

Recommended Location:
{location}

Suitability Score:
{score_text}/100

Rank:
#{ranking}

Evaluated Locations:
{len(locations)}

==================================================
AUTHORITATIVE RANKING
==================================================

{ranking_data}

==================================================
SELECTED LOCATION METRICS
==================================================

Temperature:
{temperature}

Cooling Score:
{cooling_score}

Thermal Score:
{thermal_score}

Solar GHI:
{solar_ghi}

Solar DNI:
{solar_dni}

==================================================
COMPARISON LOCATION
==================================================

Location:
{second_location.get("name") if second_location else "N/A"}

Score:
{f"{second_score:.2f}" if second_score is not None else "N/A"}

Score Difference:
{f"{score_difference:.2f}" if score_difference is not None else "N/A"}

==================================================
AUTHORITATIVE RANKING STATEMENT
==================================================

{ranking_statement}

This statement is generated by the application.
Do not modify its meaning.

==================================================
NON-NEGOTIABLE DATA INTEGRITY RULES
==================================================

1. RECOMMENDATION IS LOCKED

The recommended location is exactly:

{location}

You MUST use exactly this location.

Never replace it.

Never recommend another location.

Never suggest an alternative.

Never question the recommendation.

--------------------------------------------------

2. SCORE IS LOCKED

The authoritative score is exactly:

{score_text}/100

You MUST reproduce this exact value.

Never calculate a score.

Never estimate a score.

Never round it differently.

Never output another suitability score.

--------------------------------------------------

3. RANK IS LOCKED

The authoritative rank is:

#{ranking}

Use exactly this rank.

Do not recalculate or reinterpret ranking.

--------------------------------------------------

4. RANKING IS APPLICATION-CONTROLLED

The ranking was produced by the application.

The LLM MUST NOT create, modify, or infer a ranking.

Use the supplied authoritative ranking statement.

--------------------------------------------------

5. USE ONLY PROVIDED FACTS

Every factual statement must be directly supported
by the supplied data.

Do NOT invent facts, causes, explanations,
benchmarks, thresholds, standards, costs,
engineering conclusions, business benefits,
energy savings, infrastructure capabilities,
or environmental claims.

--------------------------------------------------

6. DO NOT CREATE CAUSAL RELATIONSHIPS

Do NOT create unsupported cause-and-effect relationships.

Do NOT say:

"because the temperature is lower"

"therefore cooling costs are lower"

"this improves energy efficiency"

"this reduces operating costs"

"this improves reliability"

"this reduces risk"

unless that exact relationship is explicitly provided
in the input data.

--------------------------------------------------

7. TEMPERATURE

Temperature may ONLY be reported as a numerical
observed metric.

Do NOT describe temperature as:

good
bad
favorable
unfavorable
ideal
extreme
comfortable
uncomfortable

--------------------------------------------------

8. COOLING SCORE

If mentioned, call it ONLY:

"cooling efficiency"

Do NOT call it:

cooling performance
energy efficiency
cooling cost
cooling savings
optimal cooling
excellent cooling

--------------------------------------------------

9. THERMAL SCORE

If mentioned, call it ONLY:

"technical infrastructure metric"

Do NOT call it:

thermal stability
thermal performance
infrastructure quality
superior infrastructure
excellent infrastructure

--------------------------------------------------

10. SOLAR METRICS

Solar GHI and Solar DNI may ONLY be reported
as numerical values.

Do NOT infer:

energy generation
renewable energy availability
energy savings
sustainability
cost reduction

--------------------------------------------------

11. NO INTERPRETATION OF SCORE MAGNITUDE

Do NOT label the overall suitability score as:

Low
Moderate
High
Poor
Good
Excellent

The score must be reported only as:

{score_text}/100

--------------------------------------------------

12. METRIC COMPARISONS

Do NOT claim that an individual metric is:

best
highest
strongest
superior
excellent
optimal

unless explicitly confirmed by authoritative data.

--------------------------------------------------

13. FORBIDDEN CLAIMS

Do NOT claim:

safety
danger
risk level
cost reduction
energy savings
sustainability
reliability
resilience
operational benefit
financial benefit
engineering superiority
infrastructure superiority

--------------------------------------------------

14. FORBIDDEN LANGUAGE

Do NOT use:

excellent
optimal
ideal
perfect
superior
best climate
good climate
bad climate
favorable climate
unfavorable climate
comfortable
comfort
discomfort
safe
unsafe
danger
dangerous
minimal risk
low risk
high risk
energy saving
energy savings
lower cost
cost reduction
sustainable
sustainability
efficient infrastructure
superior infrastructure
excellent infrastructure
optimal cooling
optimal performance
thermal stability
thermal performance

--------------------------------------------------

15. NO MARKDOWN

The output MUST NOT contain:

headings
titles
bullet points
numbered lists
bold text
italic text
Markdown symbols
quotation marks
labels

--------------------------------------------------

16. EXACTLY ONE PARAGRAPH

Return exactly ONE paragraph.

No headings.

No line breaks.

No sections.

--------------------------------------------------

17. LENGTH

Write approximately 70–110 words.

Be concise.

Do not repeat information unnecessarily.

--------------------------------------------------

18. REQUIRED CONTENT

The paragraph MUST contain:

A. The recommended location:
{location}

B. The exact suitability score:
{score_text}/100

C. At least one numerical metric from the selected location.

D. A statement that the recommendation is based on
the AIXLocate scoring system.

E. The authoritative ranking information.

F. The final sentence MUST communicate the exact meaning
of the supplied authoritative ranking statement:

{ranking_statement}

Do not change the rank.

Do not invent a different ranking.

--------------------------------------------------

FINAL INSTRUCTION

Generate ONLY the final one-paragraph report.

Do not explain your reasoning.

Do not mention these instructions.

Do not mention the prompt.

Do not mention that you are an AI.

Return exactly ONE factual paragraph.
"""

    # ==================================================
    # CALL AI WRITER
    # ==================================================

    report_text = ask_llm(prompt)

    # ==================================================
    # BASIC OUTPUT CLEANUP
    # ==================================================

    report_text = report_text.strip()

    # Remove Markdown emphasis
    report_text = report_text.replace("**", "")
    report_text = report_text.replace("__", "")

    # Remove accidental Markdown headings
    report_text = report_text.replace("#", "")

    # Remove accidental bullet prefixes
    lines = []

    for line in report_text.splitlines():
        line = line.strip()

        if not line:
            continue

        if line.startswith("- "):
            line = line[2:].strip()

        if line.startswith("• "):
            line = line[2:].strip()

        lines.append(line)

    # Collapse everything into one paragraph
    report_text = " ".join(lines)

    # ==================================================
    # AUTHORITATIVE SCORE PROTECTION
    #
    # The score returned to the application ALWAYS comes
    # directly from the scoring engine.
    # ==================================================

    return {
        "report": report_text,
        "report_score": score,
    }